Repository solecms/soleink, pull requests merged in 2024-08, with the labels that each got.

#109 :recycle: Move PR to Review #64
  .github/scripts/update-project-status.js
  .github/workflows/mv-issue-backlog.yml
  .github/workflows/pr-status-update.yml
  src/lib/workflow/update-project-status.js
  tsconfig.json
Labels: workflow

#111 :recycle: :heavy_plus_sign: Include Remaining Workflow Badges
  README.md
Labels: documentation, workflow

#113 Create Issue Template #6
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/infrastructure-workflow/bug_report.md
  .github/ISSUE_TEMPLATE/infrastructure-workflow/new_feature.md
Labels: workflow

#114 Issue templates #6
  .github/ISSUE_TEMPLATE/config.yml
Labels: workflow, Infrastructure-Workflow

#115 Issue templates #6
  .github/ISSUE_TEMPLATE/config.yml
Labels: Infrastructure-Workflow

#119 :recycle: Update parcel config
  .parcelrc
  package.json
Labels: enhancement
